# 公共配置文件
spring:
  application:
    name: pointsearch_backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    #    store-type: redis
    # 30 天过期
    timeout: 2592000
  #    redis:
  #      flush-mode: on_save # 保存时刷新
  #      namespace: springSession # 命令空间

  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip地址:端口号/数据库?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: 用户名
    password: 密码
    # Redis 配置
    # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: ip地址
    port: 端口号
    timeout: 5000
    password: 密码

  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  elasticsearch:
    uris: http://ip地址:端口号
    username: 用户名
    password: 密码

  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: ip地址
  port: 端口号
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: ''
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: ip地址
        port: 端口号
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
dubbo:
  application:
    name: 用户名
  protocol:
    name: dubbo
    port: 端口
  registry:
    id: nacos-registry
    address: nacos://ip地址:端口号